// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotM1JCQOPRyX9MYo34LJgsQYp3tfPlUs',
    appId: '1:440779755870:web:75b4900b8b974f0b0f3fcf',
    messagingSenderId: '440779755870',
    projectId: 'mynotes-flutter-fidel-fuentes',
    authDomain: 'mynotes-flutter-fidel-fuentes.firebaseapp.com',
    storageBucket: 'mynotes-flutter-fidel-fuentes.appspot.com',
    measurementId: 'G-753HBC4V3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJ_1omKX_p-HpT2h8z77tkoFSgc41_X4',
    appId: '1:440779755870:android:68f56bdb01b3684f0f3fcf',
    messagingSenderId: '440779755870',
    projectId: 'mynotes-flutter-fidel-fuentes',
    storageBucket: 'mynotes-flutter-fidel-fuentes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAZL5o3ZvPpZ79hwaAg3gTnVDlh5VuAo',
    appId: '1:440779755870:ios:fc070e3ef457753b0f3fcf',
    messagingSenderId: '440779755870',
    projectId: 'mynotes-flutter-fidel-fuentes',
    storageBucket: 'mynotes-flutter-fidel-fuentes.appspot.com',
    iosBundleId: 'com.arrancando.mynotes',
  );
}
